### ISSUE TITLE
Remove usage of Electron `remote` 

### ISSUE THREAD

**Issue by vhashimotoo** [electron/fiddle#418]
In Electron from version 10 `enableRemoteModule` default value changed to `false`. This issue created to track replacing the `remote` import by the `IPC` layer.

1. [x] [`src/renderer/components/show-me/app.tsx`] (https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx) (Need to figure where it's used)
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L18
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L20
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L21
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L45
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L63
	- https://github.com/electron/fiddle/blob/374a85e2f65c5acf99f62001ade139ae0e29e441/src/renderer/components/show-me/app.tsx#L71
2. [x] [`src/renderer/components/chrome-mac.tsx`](https://github.com/electron/fiddle/blob/dca2cd67e545dbe39ca705db526c7325eb25a111/src/renderer/components/chrome-mac.tsx) (See #598)
	- https://github.com/electron/fiddle/blob/dca2cd67e545dbe39ca705db526c7325eb25a111/src/renderer/components/chrome-mac.tsx#L15
	- https://github.com/electron/fiddle/blob/dca2cd67e545dbe39ca705db526c7325eb25a111/src/renderer/components/chrome-mac.tsx#L16
3. [x] [`src/renderer/constants.ts`](https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/constants.ts)
	- https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/constants.ts#L10
	- https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/constants.ts#L11
4. [x] [`src/utils/app-data-dir.ts`](https://github.com/electron/fiddle/blob/66536a52609b066c44f7069e90e5df2cf131c0ea/src/utils/app-data-dir.ts) (See #430)
	- https://github.com/electron/fiddle/blob/66536a52609b066c44f7069e90e5df2cf131c0ea/src/utils/app-data-dir.ts#L14
5. [x] [`src/renderer/touch-bar-manager.ts`](https://github.com/electron/fiddle/blob/98a358b75630c2ba025f26bb9056e99d7f295a7e/src/renderer/touch-bar-manager.ts) (See #562)
	- https://github.com/electron/fiddle/blob/98a358b75630c2ba025f26bb9056e99d7f295a7e/src/renderer/touch-bar-manager.ts#L13
	- https://github.com/electron/fiddle/blob/98a358b75630c2ba025f26bb9056e99d7f295a7e/src/renderer/touch-bar-manager.ts#L130
6. [x] [`src/renderer/state.ts`](https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/state.ts) (See #423)
	- https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/state.ts#L191
	- https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/state.ts#L192
	- https://github.com/electron/fiddle/blob/b98472f973ecb60dd4f2fe07b94be4ae3d658cef/src/renderer/state.ts#L195

**Comment by ckerr** [comment]
...I *think*  this issue is fixed as of @erickzhao's last commit on this? I don't see remote being imported/required anywhere in `master` now.

**Comment by erickzhao** [comment]
@ckerr the last step is disabling the `enableRemoteModule` flag and removing instances of `remote` from the test mocks. Currently in progress! 🧑‍🏭

**Comment by vhashimotoo** [comment]
🙇‍♂️
